# Generated by Django 5.1.5 on 2025-02-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='name_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_text',
            field=models.CharField(max_length=200),
        ),
    ]
