# Generated by Django 5.1.5 on 2025-02-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_response_user_alter_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
