# Generated by Django 5.1.5 on 2025-02-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_response_user_remove_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='latest_date',
        ),
    ]
